"""
Generated Contract Model
Stores contracts generated by the AI system.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship

from app.database import Base


class GeneratedContract(Base):
    """Model for storing generated contracts."""
    __tablename__ = 'generated_contracts'
    
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=True, index=True)
    
    # Contract details
    category = Column(String(100), nullable=False)
    requirements = Column(Text, nullable=False)
    generated_text = Column(Text, nullable=False)
    
    # Metadata
    template_names = Column(JSON, default=list)
    sources = Column(JSON, default=list)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    user = relationship('User', back_populates='generated_contracts')
    
    def __repr__(self):
        return f'<GeneratedContract {self.id} ({self.category})>'
    
    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'category': self.category,
            'requirements': self.requirements,
            'generated_text': self.generated_text,
            'template_names': self.template_names or [],
            'sources': self.sources or [],
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }
